@echo off
setlocal EnableDelayedExpansion

:: AllInOne_Cleaner.bat
:: Single-file wrapper that creates and runs an embedded PowerShell script
:: Requires: Run as Administrator. Provides deep-clean, registry clean, performance, startup cleanup, SSD optimizations.
:: Safety: Dry-run by default. Backups are created before destructive actions.

:: Check admin
openfiles >nul 2>&1
if %errorlevel% neq 0 (
  echo This script must be run as Administrator. Right-click -> Run as administrator.
  pause
  exit /b 1
)

:: Create temp folder for PS1 and outputs
set "TMPDIR=%temp%\AllInOneCleaner_%random%%random%"
mkdir "%TMPDIR%" >nul 2>&1

set "PS1=%TMPDIR%\AllInOne_Cleaner_core.ps1"
set "LOG=%TMPDIR%\Cleaner_log.txt"
set "BACKUPZIP=%TMPDIR%\Cleaner_backups.zip"

:: Write embedded PowerShell script
> "%PS1%" (
  echo Param()
  echo # AllInOne Deep Cleaner PowerShell core
  echo.
  echo function Write-Log {
  echo "    param(\$Text)"
  echo "    \$ts=(Get-Date).ToString('yyyy-MM-dd HH:mm:ss')"
  echo "    \"\$ts`t\$Text\" | Tee-Object -FilePath '%LOG%' -Append"
  echo "}"
  echo.
  echo function Test-Admin {
  echo "    if (-not ([bool]([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] 'Administrator'))) {"
  echo "        Write-Host 'ERROR: Run this script as Administrator.' -ForegroundColor Red; exit 1"
  echo "    }"
  echo "}"
  echo.
  echo Test-Admin
  echo "Write-Log '=== AllInOne Cleaner started ==='"
  echo.
  echo "Add-Type -AssemblyName PresentationFramework"
  echo.
  echo "# --- Utility: backup and zip files ---"
  echo "function Backup-Paths {"
  echo "    param(\$Paths)"
  echo "    if (-not \$Paths -or \$Paths.Count -eq 0) { return }"
  echo "    \$tmpFolder = Join-Path '%TMPDIR%' 'backup_' + (Get-Date -Format yyyyMMdd_HHmmss)"
  echo "    New-Item -ItemType Directory -Path \$tmpFolder | Out-Null"
  echo "    foreach (\$p in \$Paths) {"
  echo "        try {"
  echo "            if (Test-Path \$p) {"
  echo "                \$dest = Join-Path \$tmpFolder ((Split-Path \$p -Leaf) -replace '[\\\\/:*?\"<>|]','_')"
  echo "                Copy-Item -LiteralPath \$p -Destination \$dest -Recurse -Force -ErrorAction SilentlyContinue"
  echo "                Write-Log \"BACKED UP \$p -> \$dest\""
  echo "            } else { Write-Log \"SKIP BACKUP (not found) \$p\" }"
  echo "        } catch { Write-Log \"ERROR backing up \$p : \$_\" }"
  echo "    }"
  echo "    # compress"
  echo "    try {"
  echo "        Compress-Archive -Path (Join-Path \$tmpFolder '*') -DestinationPath '%BACKUPZIP%' -Force -ErrorAction SilentlyContinue"
  echo "        Write-Log \"Created backup ZIP: %BACKUPZIP%\""
  echo "    } catch { Write-Log \"ERROR creating backup zip: \$_\" }"
  echo "}"
  echo.
  echo "# --- Deep Cleaner (dry-run list, optional execute) ---"
  echo "function Deep-Cleaner {"
  echo "    param([switch]\$Execute, [switch]\$Aggressive)"
  echo "    Write-Host 'Building list of targets...'; Write-Log 'Action: Deep-Cleaner (Execute=' + \$Execute + ' Aggressive=' + \$Aggressive + ')' "
  echo "    \$plans = @()"
  echo "    \$plans += \"\$env:windir\\Temp\\*\""
  echo "    \$plans += \"\$env:LOCALAPPDATA\\Temp\\*\""
  echo "    \$plans += \"C:\\Windows\\Prefetch\\*\""
  echo "    \$plans += \"C:\\Windows\\SoftwareDistribution\\Download\\*\""
  echo "    \$plans += \"C:\\Windows\\DeliveryOptimization\\*\""
  echo "    \$plans += \"\$env:LOCALAPPDATA\\Microsoft\\Windows\\Explorer\\thumbcache_*\""
  echo "    \$plans += \"C:\\Windows\\Installer\\*.tmp\""
  echo "    \$plans += \"C:\\Windows\\Minidump\\*\""
  echo "    \$plans += \"C:\\Windows\\Memory.dmp\""
  echo "    \$plans += \"C:\\$Recycle.Bin\\*\""
  echo "    \$plans += \"\$env:LOCALAPPDATA\\Google\\Chrome\\User Data\\Default\\Cache\\*\""
  echo "    \$plans += \"\$env:LOCALAPPDATA\\Microsoft\\Edge\\User Data\\Default\\Cache\\*\""
  echo "    \$plans += \"\$env:APPDATA\\Mozilla\\Firefox\\Profiles\\*\\cache2\\*\""
  echo "    \$plans += \"C:\\ProgramData\\Package Cache\\*\""
  echo "    if (\$Aggressive) { \$plans += 'C:\\Windows.old\\*'; \$plans += 'SRP:CLEAR'; \$plans += 'EVENTLOGS:Application'; \$plans += 'EVENTLOGS:System' }"
  echo ""
  echo "    # Dry-run estimate"
  echo "    \$toDelete = @()"
  echo "    foreach (\$p in \$plans) {"
  echo "        if (\$p -like 'EVENTLOGS:*' -or \$p -eq 'SRP:CLEAR') { \$toDelete += \$p; continue }"
  echo "        try { \$matches = Get-ChildItem -Path \$p -Recurse -Force -ErrorAction SilentlyContinue } catch { \$matches = \$null }"
  echo "        if (\$matches) { foreach (\$m in \$matches) { \$toDelete += \$m.FullName } }"
  echo "    }"
  echo "    Write-Host ('Planned deletions: ' + \$toDelete.Count + ' items')"
  echo "    Write-Log ('Planned deletions count: ' + \$toDelete.Count)"
  echo "    if (-not \$Execute) { Write-Host 'Dry-run: no files deleted. Use Execute switch to remove items.'; return }"
  echo ""
  echo "    # Backup before deletion (compress top-level targets)"
  echo "    \$topTargets = \$plans | Where-Object { \$_ -notlike 'EVENTLOGS:*' -and \$_ -ne 'SRP:CLEAR' }"
  echo "    Backup-Paths -Paths \$topTargets"
  echo ""
  echo "    # Stop services that lock update files"
  echo "    Write-Log 'Stopping wuauserv,bits (attempt)'; Stop-Service wuauserv -ErrorAction SilentlyContinue; Stop-Service bits -ErrorAction SilentlyContinue"
  echo ""
  echo "    foreach (\$p in \$plans) {"
  echo "        if (\$p -like 'EVENTLOGS:*') { \$logName = \$p.Split(':')[1]; try { wevtutil cl \$logName; Write-Log \"CLEARED_EVENTLOG \$logName\" } catch { Write-Log \"ERR clearing \$logName : \$_\" } ; continue }"
  echo "        if (\$p -eq 'SRP:CLEAR') { try { vssadmin delete shadows /all /quiet; Write-Log 'CLEARED_SRP' } catch { Write-Log 'ERR clearing SRP' } ; continue }"
  echo "        try {"
  echo "            \$items = Get-ChildItem -Path \$p -Recurse -Force -ErrorAction SilentlyContinue"
  echo "            if (\$items) { foreach (\$i in \$items) { Remove-Item -LiteralPath \$i.FullName -Recurse -Force -ErrorAction SilentlyContinue; Write-Log \"REMOVED \$(\$i.FullName)\" } } else { Write-Log \"No items found for \$p\" }"
  echo "        } catch { Write-Log \"ERROR processing \$p : \$_\" }"
  echo "    }"
  echo "    Start-Service wuauserv -ErrorAction SilentlyContinue; Start-Service bits -ErrorAction SilentlyContinue"
  echo "    Write-Log 'Deep cleanup finished.'"
  echo "}"
  echo.
  echo "# --- Registry Cleaner (safe) ---"
  echo "function Registry-Cleaner {"
  echo "    param([switch]\$Execute)"
  echo "    Write-Host 'Registry Cleaner: this will attempt to remove obvious orphan/unreferenced Run entries, MRU lists for removed apps, and invalid uninstall keys.'"
  echo "    Write-Log 'Action: Registry-Cleaner (Execute=' + \$Execute + ')'"
  echo ""
  echo "    # Export keys we will touch"
  echo "    \$exportFiles = @()"
  echo "    \$export1 = Join-Path '%TMPDIR%' 'HKCU_Run_backup.reg'"
  echo "    reg export 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' \$export1 /y >\$null 2>\$null; \$exportFiles += \$export1"
  echo "    \$export2 = Join-Path '%TMPDIR%' 'Uninstall_All_backup.reg'"
  echo "    reg export 'HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall' \$export2 /y >\$null 2>\$null; \$exportFiles += \$export2"
  echo "    Write-Log \"Registry exports created: \$($exportFiles -join ', ')\""
  echo ""
  echo "    # Gather Run entries"
  echo "    \$runHKCU = Get-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -ErrorAction SilentlyContinue"
  echo "    if (-not \$runHKCU) { Write-Host 'No HKCU Run entries found.'; Write-Log 'No HKCU Run entries'; return }"
  echo "    \$entries = @()"
  echo "    foreach (\$prop in \$runHKCU.PSObject.Properties) { if (\$prop.Name -ne 'PSPath' -and \$prop.Name -ne 'PSParentPath' -and \$prop.Name -ne 'PSChildName' -and \$prop.Name -ne 'PSProvider') { \$entries += [PSCustomObject]@{Name=\$prop.Name; Value=\$prop.Value} } }"
  echo "    Write-Host 'Detected HKCU Run startup items:'"
  echo "    \$i=0; foreach (\$e in \$entries) { \$i++; Write-Host (\"[\$i] \$($e.Name) => \$($e.Value)\") }"
  echo "    if (-not \$Execute) { Write-Host 'Dry-run: no registry changes.'; return }"
  echo ""
  echo "    # Ask which to remove"
  echo "    \$toRemove = Read-Host 'Enter comma-separated numbers to remove (or ALL):'"
  echo "    if (\$toRemove.Trim().ToUpper() -eq 'ALL') { \$sel = 1..\$entries.Count } else { \$sel = \$toRemove -split ',' | ForEach-Object { [int]_\ } }"
  echo "    foreach (\$n in \$sel) {"
  echo "        \$idx = [int]\$n - 1"
  echo "        if (\$idx -ge 0 -and \$idx -lt \$entries.Count) {"
  echo "            \$name = \$entries[\$idx].Name"
  echo "            try { Remove-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Name \$name -ErrorAction Stop; Write-Log \"Removed Run entry: \$name\"; Write-Host \"Removed: \$name\" } catch { Write-Log \"ERROR removing Run \$name: \$_\"; Write-Host \"Failed to remove: \$name\" }"
  echo "        }"
  echo "    }"
  echo "    Write-Log 'Registry cleaning finished.'"
  echo "}"
  echo.
  echo "# --- Performance Booster (disable bloat services) ---"
  echo "function Performance-Booster {"
  echo "    param([switch]\$Execute)"
  echo "    Write-Host 'Performance Booster: Suggests disabling non-critical services (safe list). Review before applying.'"
  echo "    \$candidates = @("
  echo "        @{Name='DiagTrack'; Display='Connected User Experiences and Telemetry (DiagTrack)'; Service='DiagTrack'},"
  echo "        @{Name='WMPNetworkSvc'; Display='Windows Media Player Network Sharing Service'; Service='WMPNetworkSvc'},"
  echo "        @{Name='wuauserv'; Display='Windows Update (recommended to leave enabled)'; Service='wuauserv'},"
  echo "        @{Name='XblGameSave'; Display='Xbox Live Game Save'; Service='XblGameSave'}"
  echo "    )"
  echo "    Write-Host 'Candidates (review):'"
  echo "    \$i=0; foreach (\$c in \$candidates) { \$i++; Write-Host (\"[\$i] \$($c.Display) (svc:\$($c.Service))\") }"
  echo "    if (-not \$Execute) { Write-Host 'Dry-run: no service changes.'; return }"
  echo "    \$sel = Read-Host 'Enter numbers to disable (comma) or ALL to disable all listed:'"
  echo "    if (\$sel.Trim().ToUpper() -eq 'ALL') { \$nums = 1..\$candidates.Count } else { \$nums = \$sel -split ',' | ForEach-Object { [int]_\ } }"
  echo "    foreach (\$n in \$nums) {"
  echo "        \$idx = [int]\$n - 1"
  echo "        if (\$idx -ge 0 -and \$idx -lt \$candidates.Count) {"
  echo "            \$svc = \$candidates[\$idx].Service"
  echo "            try { Set-Service -Name \$svc -StartupType Disabled -ErrorAction Stop; Stop-Service -Name \$svc -Force -ErrorAction SilentlyContinue; Write-Log \"Disabled service: \$svc\"; Write-Host \"Disabled: \$svc\" } catch { Write-Log \"ERROR disabling \$svc : \$_\"; Write-Host \"Failed: \$svc\" }"
  echo "        }"
  echo "    }"
  echo "    Write-Log 'Performance booster finished.'"
  echo "}"
  echo.
  echo "# --- Startup Program Cleaner (lists, remove) ---"
  echo "function Startup-Cleaner {"
  echo "    param([switch]\$Execute)"
  echo "    Write-Host 'Startup Cleaner: scanning Run keys and Scheduled Tasks for startup entries...'; Write-Log 'Action: Startup-Cleaner (Execute=' + \$Execute + ')'"
  echo "    \$runHKCU = Get-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -ErrorAction SilentlyContinue"
  echo "    \$list = @()"
  echo "    if (\$runHKCU) { foreach (\$prop in \$runHKCU.PSObject.Properties) { if (\$prop.Name -notmatch '^PS') { \$list += [PSCustomObject]@{Type='HKCU\\Run'; Name=\$prop.Name; Value=\$prop.Value} } } }"
  echo "    \$runHKLM = Get-ItemProperty -Path 'HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -ErrorAction SilentlyContinue"
  echo "    if (\$runHKLM) { foreach (\$p in \$runHKLM.PSObject.Properties) { if (\$p.Name -notmatch '^PS') { \$list += [PSCustomObject]@{Type='HKLM\\Run'; Name=\$p.Name; Value=\$p.Value} } } }"
  echo "    # scheduled tasks that run at logon"
  echo "    \$tasks = schtasks /Query /FO LIST /V 2>$null | Out-String"
  echo "    # Show list"
  echo "    if (\$list.Count -eq 0) { Write-Host 'No Run entries found.'; return }"
  echo "    \$i=0; foreach (\$it in \$list) { \$i++; Write-Host (\"[\$i] [\$($it.Type)] \$($it.Name) => \$($it.Value)\") }"
  echo "    if (-not \$Execute) { Write-Host 'Dry-run: nothing removed.'; return }"
  echo "    \$sel = Read-Host 'Enter numbers to remove (comma) or ALL:'"
  echo "    if (\$sel.Trim().ToUpper() -eq 'ALL') { \$selArr = 1..\$list.Count } else { \$selArr = \$sel -split ',' | ForEach-Object { [int]_\ } }"
  echo "    foreach (\$n in \$selArr) {"
  echo "        \$idx = [int]\$n - 1"
  echo "        if (\$idx -ge 0 -and \$idx -lt \$list.Count) {"
  echo "            \$entry = \$list[\$idx]"
  echo "            try {"
  echo "                if (\$entry.Type -eq 'HKCU\\Run') { Remove-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Name \$entry.Name -ErrorAction Stop; Write-Log \"Removed startup: \$entry.Name (HKCU)\" }"
  echo "                elseif (\$entry.Type -eq 'HKLM\\Run') { Remove-ItemProperty -Path 'HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Name \$entry.Name -ErrorAction Stop; Write-Log \"Removed startup: \$entry.Name (HKLM)\" }"
  echo "                Write-Host \"Removed: \$($entry.Name)\""
  echo "            } catch { Write-Log \"ERROR removing startup \$($entry.Name): \$_\" }"
  echo "        }"
  echo "    }"
  echo "    Write-Log 'Startup cleaning finished.'"
  echo "}"
  echo.
  echo "# --- SSD Optimizations ---"
  echo "function SSD-Optimize {"
  echo "    param([switch]\$Execute)"
  echo "    Write-Host 'SSD Optimization: checks TRIM and runs light optimization for SSDs.'; Write-Log 'Action: SSD-Optimize (Execute=' + \$Execute + ')'"
  echo "    try { \$diskInfo = Get-PhysicalDisk -ErrorAction SilentlyContinue } catch { \$diskInfo = \$null }"
  echo "    \$isSSD = \$false"
  echo "    if (\$diskInfo) { if (\$diskInfo.MediaType -contains 'SSD') { \$isSSD = \$true } }"
  echo "    # fallback: check defrag status"
  echo "    if (-not \$isSSD) {"
  echo "        \$drv = Get-Volume -DriveLetter C -ErrorAction SilentlyContinue"
  echo "        if (\$drv -and \$drv.FileSystemLabel) { \$isSSD = (Get-PhysicalDisk | Where-Object MediaType -eq 'SSD') -ne \$null }"
  echo "    }"
  echo "    Write-Host ('SSD detected: ' + \$isSSD)"
  echo "    if (-not \$Execute) { Write-Host 'Dry-run: no changes. Use Execute to apply TRIM/optimize.'; return }"
  echo "    if (\$isSSD) {"
  echo "        try { fsutil behavior query DisableDeleteNotify | Out-Null ; Write-Log 'TRIM check performed'; Optimize-Volume -DriveLetter C -ReTrim -Verbose; Write-Log 'ReTrim requested'; } catch { Write-Log 'ERROR SSD Trim/Optimize: ' + \$_ }"
  echo "        # disable scheduled defrag (Windows handles SSDs) - optional"
  echo "        try { Disable-ScheduledTask -TaskName 'ScheduledDefrag' -ErrorAction SilentlyContinue; Write-Log 'Disabled ScheduledDefrag task (if existed)'; } catch { }"
  echo "    } else { Write-Log 'No SSD detected; skipping TRIM/optimize' }"
  echo "    Write-Log 'SSD optimization finished.'"
  echo "}"
  echo.
  echo "# --- Simple GUI menu using WPF ---"
  echo "function Show-GUI {"
  echo "    [xml] \$xaml = @'\"
  echo "    <Window xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' Title='AllInOne Cleaner' Width='720' Height='520'>"
  echo "      <Grid Margin='10'>"
  echo "        <Grid.RowDefinitions><RowDefinition Height='Auto'/><RowDefinition Height='*'/></Grid.RowDefinitions>"
  echo "        <TextBlock FontSize='16' FontWeight='Bold'>AllInOne Cleaner — Dry-run by default. Click an action then CONFIRM.</TextBlock>"
  echo "        <StackPanel Grid.Row='1' Margin='0,10,0,0'>"
  echo "          <WrapPanel Margin='0,0,0,8'>"
  echo "            <Button Name='btnDeep' Width='160' Margin='4'>Deep Cleaner</Button>"
  echo "            <Button Name='btnRegistry' Width='160' Margin='4'>Registry Cleaner</Button>"
  echo "            <Button Name='btnPerf' Width='160' Margin='4'>Performance Booster</Button>"
  echo "            <Button Name='btnStartup' Width='160' Margin='4'>Startup Cleaner</Button>"
  echo "          </WrapPanel>"
  echo "          <WrapPanel Margin='0,0,0,8'>"
  echo "            <Button Name='btnSSD' Width='160' Margin='4'>SSD Optimize</Button>"
  echo "            <CheckBox Name='chkAgg' Margin='8' VerticalAlignment='Center'>Aggressive</CheckBox>"
  echo "            <CheckBox Name='chkExec' Name='chkExec' Margin='8' VerticalAlignment='Center'>Execute (apply changes)</CheckBox>"
  echo "            <Button Name='btnViewLog' Width='160' Margin='4'>Open Log Folder</Button>"
  echo "          </WrapPanel>"
  echo "          <TextBox Name='txtStatus' Height='260' IsReadOnly='True' TextWrapping='Wrap' VerticalScrollBarVisibility='Auto'/>"
  echo "        </StackPanel>"
  echo "      </Grid>"
  echo "    </Window>"
  echo "'@"
  echo "    \$reader = (New-Object System.Xml.XmlNodeReader \$xaml)"
  echo "    \$form = [Windows.Markup.XamlReader]::Load(\$reader)"
  echo "    \$btnDeep = \$form.FindName('btnDeep')"
  echo "    \$btnRegistry = \$form.FindName('btnRegistry')"
  echo "    \$btnPerf = \$form.FindName('btnPerf')"
  echo "    \$btnStartup = \$form.FindName('btnStartup')"
  echo "    \$btnSSD = \$form.FindName('btnSSD')"
  echo "    \$chkAgg = \$form.FindName('chkAgg')"
  echo "    \$chkExec = \$form.FindName('chkExec')"
  echo "    \$txtStatus = \$form.FindName('txtStatus')"
  echo "    \$btnViewLog = \$form.FindName('btnViewLog')"
  echo ""
  echo "    \$btnDeep.Add_Click({"
  echo "        \$txtStatus.AppendText('Running Deep Cleaner (dry-run) ...`r`n')"
  echo "        \$txtStatus.ScrollToEnd()"
  echo "        Deep-Cleaner -Execute:\$chkExec.IsChecked -Aggressive:\$chkAgg.IsChecked"
  echo "        \$txtStatus.AppendText('Deep Cleaner finished.`r`n')"
  echo "        \$txtStatus.ScrollToEnd()"
  echo "    })"
  echo "    \$btnRegistry.Add_Click({"
  echo "        \$txtStatus.AppendText('Starting Registry Cleaner ...`r`n')"
  echo "        Registry-Cleaner -Execute:\$chkExec.IsChecked"
  echo "        \$txtStatus.AppendText('Registry Cleaner finished.`r`n')"
  echo "    })"
  echo "    \$btnPerf.Add_Click({"
  echo "        \$txtStatus.AppendText('Performance Booster ...`r`n')"
  echo "        Performance-Booster -Execute:\$chkExec.IsChecked"
  echo "        \$txtStatus.AppendText('Performance Booster finished.`r`n')"
  echo "    })"
  echo "    \$btnStartup.Add_Click({"
  echo "        \$txtStatus.AppendText('Startup Cleaner ...`r`n')"
  echo "        Startup-Cleaner -Execute:\$chkExec.IsChecked"
  echo "        \$txtStatus.AppendText('Startup Cleaner finished.`r`n')"
  echo "    })"
  echo "    \$btnSSD.Add_Click({"
  echo "        \$txtStatus.AppendText('SSD Optimize ...`r`n')"
  echo "        SSD-Optimize -Execute:\$chkExec.IsChecked"
  echo "        \$txtStatus.AppendText('SSD Optimize finished.`r`n')"
  echo "    })"
  echo "    \$btnViewLog.Add_Click({ Start-Process explorer.exe '%TMPDIR%' })"
  echo ""
  echo "    \$form.ShowDialog() | Out-Null"
  echo "}"
  echo.
  echo "# If script invoked directly (no GUI), show GUI by default"
  echo "Show-GUI"
  echo "Write-Log '=== AllInOne Cleaner finished ==='"
)

:: Run the PowerShell script
powershell -NoProfile -ExecutionPolicy Bypass -File "%PS1%"

echo.
echo Logs and backups saved to: %TMPDIR%
echo To keep backups, copy the zip: %BACKUPZIP%
echo Press any key to remove temp files and exit, or CTRL+C to keep them.
pause >nul

:: Cleanup temp if user confirms
echo Removing temporary files...
rd /s /q "%TMPDIR%" >nul 2>&1
echo Done.
exit /b 0
